columns_mapping = {'Bike Id': 'Bike Id',
 'End Station Id': 'End Station Id',
 'End Station Name': 'End Station Name',
 'End Time': 'End Time',
 'Model': 'Model',
 'Start Station Id': 'Start Station Id',
 'Start Station Name': 'Start Station Name',
 'Start Time': 'Start Time',
 'Trip  Duration': 'Trip Duration',
 'Trip Id': 'Trip Id',
 'User Type': 'User Type',
 'from_station_id': 'Start Station Id',
 'from_station_name': 'Start Station Name',
 'to_station_id': 'End Station Id',
 'to_station_name': 'End Station Name',
 'trip_duration_seconds': 'Trip Duration',
 'trip_id': 'Trip Id',
 'trip_start_time': 'Start Time',
 'trip_stop_time': 'End Time',
 'user_type': 'User Type'}


columns_types = {'Trip Id': 'str',
                 'Start Time': 'datetime64[ns]', 
                 'End Time': 'datetime64[ns]', 
                 'Trip Duration': 'int32', 
                 'Start Station Id': 'int32', 
                 'Start Station Name': 'str', 
                 'End Station Id': 'int32', 
                 'End Station Name': 'str', 
                 'User Type': 'str'}

incomplete_columns_types = {'Trip Id': 'str',
                 'Start Time': 'datetime64[ns]', 
                 'End Time': 'datetime64[ns]', 
                 'Trip Duration': 'int32', 
                 'Start Station Name': 'str', 
                 'End Station Name': 'str', 
                 'User Type': 'str'}